### ISSUE TITLE
Routing does not work if hostname not set

### ISSUE THREAD

**Issue by AaronSadlerUK** [callumbwhyte/friendly-robots#4]
If the hostname is not set, the routing will not work and it will return the IIS 404 error rather than application 404 error.

The fact this also affects the friendly-sitemap plugin makes me think the issue lies in the routing extensions plugin

**Comment by callumbwhyte** [comment]
Thanks @AaronSadlerUK,

As commented on [friendly-sitemap/#12](https://github.com/callumbwhyte/friendly-sitemap/issues/12) this is an issue in the [Routing Extensions](https://github.com/callumbwhyte/umbraco-routing-extensions) project that needs some investigation.

Cheers,
Callum

**Comment by callumbwhyte** [comment]
Thanks to @dampee this was fixed in the Routing Extensions package. Updating that dependency to the latest version will fix this issue!
